site_name: Siddhi-IO-Prometheus
site_description: Siddhi IO Extension for Prometheus
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-io-prometheus/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-IO-Prometheus
repo_url: https://github.com/wso2-extensions/siddhi-io-prometheus
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/prometheus
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
site_favicon: images/favicon.ico
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome to WSO2 Siddhi IO Prometheus: index.md
- API Docs:
  - 2.0.0: api/2.0.0.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
  - latest: api/latest.md
  - ? ''
    : api/.md
- License: about/license.md
